# .readthedocs.yml

version: 2

build:
  image: latest

sphinx:
  configuration: conf.py

formats: all

python:
  version: "3.7"

  system_packages: true

  install:
    - requirements: requirements.txt

